KEYWORDS = {
    'Ans': 5,
    'Aim': 10,
    'Diagram': 10,
    'Introduction': 5,
    'Results': 15,
    'Conclusion': 10,
    'Abstract': 5,
    'Methodology': 10,
    'Discussion': 10,
    'References': 5,
    'Bibliography': 5,
    'Appendix': 5,
    'Hypothesis': 5,
    'Analysis': 10,
    'Observations': 5,
    'Literature Review': 10,
    'Objectives': 5,
    'Procedure': 10,
    'Findings': 10,
    'Evaluation': 5,
    'Summary': 5,
    'Recommendations': 5,
    'Limitations': 5,
    'Future Work': 5,
    'Acknowledgments': 2,
    'Table of Contents': 2,
    'Cover Page': 2,
    'Title Page': 2,
    'Problem Statement': 5,
    'Scope': 5,
    'Significance': 5,
    'Justification': 5,
    'Assumptions': 5,
    'Variables': 5,
    'Materials': 5,
    'Equipment': 5,
    'Data': 10,
    'Graphs': 5,
    'Charts': 5,
    'Tables': 5,
    'Calculations': 10,
    'Equations': 5,
    'Formulas': 5,
    'Theoretical Background': 10,
    'Experimental Setup': 10,
    'Results and Discussion': 15,
    'Conclusion and Recommendations': 10,
    'References and Bibliography': 5,
    'Annexure': 2,
    'Appendices': 2,
    'Glossary': 2,
    'Index': 2,
    'Preface': 3,
    'Foreword': 3,
    'Dedication': 2,
    'Acknowledgements': 2,
    'List of Figures': 2,
    'List of Tables': 2,
    'Executive Summary': 5,
    'Statement of the Problem': 5,
    'Research Questions': 5,
    'Definition of Terms': 5,
    'Delimitations': 5,
    'Ethical Considerations': 5,
    'Data Collection': 10,
    'Data Analysis': 10,
    'Interpretation of Results': 10,
    'Implications': 5,
    'Concluding Remarks': 5,
    'Works Cited': 5,
    'Literature Cited': 5,
    'Author Contributions': 2,
    'Funding Statement': 2,
    'Conflict of Interest Statement': 2,
    'Supplementary Materials': 2,
    'Errata': 2,
    'Corrigenda': 2
}
KEYWORDS = {
    'Ans': 5,
    'Aim': 10,
    'Diagram': 10,
    'Introduction': 5,
    'Results': 15,
    'Conclusion': 10,
    'Abstract': 5,
    'Methodology': 10,
    'Discussion': 10,
    'References': 5,
    'Bibliography': 5,
    'Appendix': 5,
    'Hypothesis': 5,
    'Analysis': 10,
    'Observations': 5,
    'Literature Review': 10,
    'Objectives': 5,
    'Procedure': 10,
    'Findings': 10,
    'Evaluation': 5,
    'Summary': 5,
    'Recommendations': 5,
    'Limitations': 5,
    'Future Work': 5,
    'Acknowledgments': 2,
    'Table of Contents': 2,
    'Cover Page': 2,
    'Title Page': 2,
    'Problem Statement': 5,
    'Scope': 5,
    'Significance': 5,
    'Justification': 5,
    'Assumptions': 5,
    'Variables': 5,
    'Materials': 5,
    'Equipment': 5,
    'Data': 10,
    'Graphs': 5,
    'Charts': 5,
    'Tables': 5,
    'Calculations': 10,
    'Equations': 5,
    'Formulas': 5,
    'Theoretical Background': 10,
    'Experimental Setup': 10,
    'Procedure': 10,
    'Results and Discussion': 15,
    'Conclusion and Recommendations': 10,
    'References and Bibliography': 5,
    'Annexure': 2,
    'Appendices': 2,
    'Glossary': 2,
    'Index': 2
}
